xlsx_sample_num: 5

dataset:
  test:
    ratio: 1.0
    num: 8
    data_paths:
      - /VITA-Audio/asset/text_chat.jsonl
      - /VITA-Audio/asset/asr.jsonl
      - /VITA-Audio/asset/tts.jsonl
      - /VITA-Audio/asset/sts.jsonl
